apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-python-app
  labels:
    app: django-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-web-app
  template:
    metadata:
      labels:
        app: django-web-app
    spec:
      containers:
      - name: python-container
        image: bhars77/web-app:v1
        env:
          - name: DB-PORT
            valueFrom:
              configMapKeyRef:
                name: test-cm
                key: db-port
        ports:
        - containerPort: 8000
